CRUD in Channel
andre-gomes-oliveira/boilerplate-nodejs-hexagonal-architecture pull request #4
Opened 2022-09-30 16:09 UTC by allysonfield

CRUD was implemented in Channel entity.

2022-09-30 16:33 UTC, andre-gomes-oliveira requested changes
pequenas correções em mensagem de erro e na validação do create.

2022-09-30 16:33 UTC, andre-gomes-oliveira commented on src/core/services/ChannelService.ts
> +    if (channelFromId) return { statusCode: 409, message: 'Canal com o mesmo código já cadastrada' };
detalhe na mensagem de erro, mudar para "Canal com o mesmo código já cadastrado"

2022-09-30 16:33 UTC, andre-gomes-oliveira commented on src/core/services/ChannelService.ts
> +    if (channelFromName) return { statusCode: 409, message: 'Canal com o mesmo nome já cadastrada' };
Mesma mudança na mensagem aqui.

2022-09-30 16:33 UTC, andre-gomes-oliveira commented on src/schemas/channelSchema.ts
> +  dataFimVigencia: Joi.date().required().format('DD/MM/YYYY'),
A data de fim da vigência não é passada no create, melhor remover essa validação.

2022-09-30 21:21 UTC, allysonfield commented on src/core/services/ChannelService.ts
> +    if (channelFromId) return { statusCode: 409, message: 'Canal com o mesmo código já cadastrada' };
Feito

2022-09-30 21:21 UTC, allysonfield commented on src/core/services/ChannelService.ts
> +    if (channelFromName) return { statusCode: 409, message: 'Canal com o mesmo nome já cadastrada' };
Feito

2022-09-30 21:22 UTC, allysonfield commented on src/schemas/channelSchema.ts
> +  dataFimVigencia: Joi.date().required().format('DD/MM/YYYY'),
Feito

2022-10-03 11:49 UTC, andre-gomes-oliveira approved these changes

2022-10-03 18:19 UTC, andre-gomes-oliveira approved these changes

2022-10-03 18:19 UTC, merged